import type {
  User,
  Venue,
  Challenge,
  PlayerStats,
  Avatar,
  ChallengeSubmission,
  UserChallengeStatus,
  PlayerWithStats,
} from '@/types';

// Mock current user (will be built up through onboarding)
export const mockUser: Partial<User> = {
  id: 'user-1',
  email: '',
  emailVerified: false,
  name: '',
  age: 0,
  ageGroup: '22-25',
  gender: 'Male',
  location: '',
  hasCompletedOnboarding: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

// Mock venues
export const mockVenues: Venue[] = [
  {
    id: 'venue-1',
    name: 'Rucker Park',
    venueType: 'court',
    sportType: 'basketball',
    address: '155th St & Frederick Douglass Blvd',
    latitude: 40.8299,
    longitude: -73.9384,
    city: 'New York',
    country: 'USA',
    activePlayerCount: 8,
    currentKingId: 'user-2',
    description: 'Famous street basketball court in Harlem',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'venue-2',
    name: 'Brooklyn Bridge Park Courts',
    venueType: 'court',
    sportType: 'basketball',
    address: 'Brooklyn Bridge Park',
    latitude: 40.6990,
    longitude: -73.9969,
    city: 'New York',
    country: 'USA',
    activePlayerCount: 12,
    currentKingId: 'user-3',
    description: 'Waterfront basketball courts with skyline views',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'venue-3',
    name: 'Central Park Soccer Fields',
    venueType: 'field',
    sportType: 'soccer',
    address: 'Central Park',
    latitude: 40.7829,
    longitude: -73.9654,
    city: 'New York',
    country: 'USA',
    activePlayerCount: 22,
    currentKingId: 'user-4',
    description: 'Premier soccer fields in Manhattan',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'venue-4',
    name: 'Prospect Park Running Track',
    venueType: 'track',
    sportType: 'running',
    address: 'Prospect Park',
    latitude: 40.6602,
    longitude: -73.9690,
    city: 'New York',
    country: 'USA',
    activePlayerCount: 15,
    currentKingId: 'user-5',
    description: '3.35-mile loop perfect for runners',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock challenges
export const mockChallenges: Challenge[] = [
  {
    id: 'challenge-1',
    venueId: 'venue-1',
    name: 'Free Throw Master',
    description: 'Make 8 out of 10 free throws',
    instructions: 'Stand at the free throw line and shoot 10 consecutive free throws. You must make at least 8 to pass.',
    challengeType: 'free_throws',
    parameters: {
      requiredShots: 10,
      minSuccessful: 8,
      timeLimit: 120,
    },
    xpReward: 100,
    difficulty: 'easy',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'challenge-2',
    venueId: 'venue-1',
    name: 'Three-Point Assassin',
    description: 'Hit 5 three-pointers in 60 seconds',
    instructions: 'Make 5 three-point shots from different positions around the arc within 60 seconds.',
    challengeType: 'three_pointers',
    parameters: {
      requiredShots: 5,
      timeLimit: 60,
    },
    xpReward: 200,
    difficulty: 'medium',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'challenge-3',
    venueId: 'venue-1',
    name: 'Layup Drill',
    description: 'Complete 20 consecutive layups alternating sides',
    instructions: 'Start from one side, make a layup, grab the rebound, go to the other side. Repeat 10 times each side.',
    challengeType: 'layups',
    parameters: {
      requiredShots: 20,
      timeLimit: 180,
    },
    xpReward: 150,
    difficulty: 'medium',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'challenge-4',
    venueId: 'venue-3',
    name: 'Penalty Kick Challenge',
    description: 'Score 7 out of 10 penalty kicks',
    instructions: 'Take 10 penalty kicks. You must score at least 7 to complete the challenge.',
    challengeType: 'penalty_kicks',
    parameters: {
      requiredShots: 10,
      minSuccessful: 7,
      timeLimit: 180,
    },
    xpReward: 150,
    difficulty: 'medium',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'challenge-5',
    venueId: 'venue-4',
    name: '5K Sprint',
    description: 'Complete a 5K run under 25 minutes',
    instructions: 'Run 5 kilometers (3.1 miles) around the track. Finish under 25 minutes to earn XP.',
    challengeType: 'sprint',
    parameters: {
      distance: '5km',
      timeLimit: 1500, // 25 minutes
    },
    xpReward: 250,
    difficulty: 'hard',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock other users
export const mockUsers: User[] = [
  {
    id: 'user-2',
    email: 'jordan.king@example.com',
    emailVerified: true,
    name: 'Jordan King',
    age: 27,
    ageGroup: '26+',
    gender: 'Male',
    location: 'Harlem, NY',
    profilePictureUrl: '/avatars/user-2.jpg',
    hasCompletedOnboarding: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'user-3',
    email: 'alex.storm@example.com',
    emailVerified: true,
    name: 'Alex Storm',
    age: 22,
    ageGroup: '22-25',
    gender: 'Female',
    location: 'Brooklyn, NY',
    profilePictureUrl: '/avatars/user-3.jpg',
    hasCompletedOnboarding: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
  },
  {
    id: 'user-4',
    email: 'carlos.silva@example.com',
    emailVerified: true,
    name: 'Carlos Silva',
    age: 24,
    ageGroup: '22-25',
    gender: 'Male',
    location: 'Manhattan, NY',
    profilePictureUrl: '/avatars/user-4.jpg',
    hasCompletedOnboarding: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'user-5',
    email: 'maya.runner@example.com',
    emailVerified: true,
    name: 'Maya Thompson',
    age: 19,
    ageGroup: '19-21',
    gender: 'Female',
    location: 'Brooklyn, NY',
    profilePictureUrl: '/avatars/user-5.jpg',
    hasCompletedOnboarding: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date(),
  },
  {
    id: 'user-6',
    email: 'mike.hoops@example.com',
    emailVerified: true,
    name: 'Mike Johnson',
    age: 30,
    ageGroup: '26+',
    gender: 'Male',
    location: 'Queens, NY',
    profilePictureUrl: '/avatars/user-6.jpg',
    hasCompletedOnboarding: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
];

// Mock player stats
export const mockPlayerStats: PlayerStats[] = [
  {
    id: 'stats-1',
    userId: 'user-2',
    totalXp: 5200,
    currentRank: 1,
    totalChallenges: 42,
    sportType: 'basketball',
    venueStatsJson: {
      'venue-1': { rank: 1, xp: 3200 },
      'venue-2': { rank: 3, xp: 2000 },
    },
    updatedAt: new Date(),
  },
  {
    id: 'stats-2',
    userId: 'user-3',
    totalXp: 4800,
    currentRank: 2,
    totalChallenges: 38,
    sportType: 'basketball',
    venueStatsJson: {
      'venue-2': { rank: 1, xp: 3500 },
      'venue-1': { rank: 5, xp: 1300 },
    },
    updatedAt: new Date(),
  },
  {
    id: 'stats-3',
    userId: 'user-4',
    totalXp: 4200,
    currentRank: 1,
    totalChallenges: 35,
    sportType: 'soccer',
    venueStatsJson: {
      'venue-3': { rank: 1, xp: 4200 },
    },
    updatedAt: new Date(),
  },
  {
    id: 'stats-4',
    userId: 'user-5',
    totalXp: 3900,
    currentRank: 1,
    totalChallenges: 28,
    sportType: 'running',
    venueStatsJson: {
      'venue-4': { rank: 1, xp: 3900 },
    },
    updatedAt: new Date(),
  },
  {
    id: 'stats-5',
    userId: 'user-6',
    totalXp: 3500,
    currentRank: 3,
    totalChallenges: 31,
    sportType: 'basketball',
    venueStatsJson: {
      'venue-1': { rank: 2, xp: 2800 },
      'venue-2': { rank: 8, xp: 700 },
    },
    updatedAt: new Date(),
  },
];

// Mock avatars
export const mockAvatars: Avatar[] = [
  {
    id: 'avatar-1',
    userId: 'user-2',
    hairColor: 'black',
    hairStyle: 'fade',
    jerseyNumber: 23,
    equippedItems: {
      torso: 'jordan-jersey-red',
      legs: 'basketball-shorts-black',
      feet: 'air-jordan-1',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'avatar-2',
    userId: 'user-3',
    hairColor: 'blonde',
    hairStyle: 'ponytail',
    jerseyNumber: 11,
    equippedItems: {
      torso: 'nike-jersey-blue',
      legs: 'basketball-shorts-white',
      feet: 'kobe-sneakers',
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Top players for rankings
export const mockTopPlayers: PlayerWithStats[] = mockUsers.slice(0, 5).map((user, index) => ({
  user,
  stats: mockPlayerStats[index],
  avatar: mockAvatars.find(a => a.userId === user.id),
}));

// Monthly challenge mock data
export const mockMonthlyChallenge = {
  id: 'monthly-1',
  title: 'November Basketball Championship',
  description: 'Compete to be the top basketball player this month!',
  sportType: 'basketball',
  startDate: new Date('2024-11-01'),
  endDate: new Date('2024-11-30'),
  prizeDescription: '$500 Nike Gift Card + Championship Trophy',
  topPlayerIds: ['user-2', 'user-3', 'user-6', 'user-1', 'user-5'],
  isActive: true,
};

// Mock sponsors
export const mockSponsors = [
  {
    id: 'sponsor-1',
    name: 'Nike',
    logoUrl: '/sponsors/nike-logo.svg',
    websiteUrl: 'https://nike.com',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sponsor-2',
    name: 'Adidas',
    logoUrl: '/sponsors/adidas-logo.svg',
    websiteUrl: 'https://adidas.com',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'sponsor-3',
    name: 'Gatorade',
    logoUrl: '/sponsors/gatorade-logo.svg',
    websiteUrl: 'https://gatorade.com',
    displayOrder: 3,
    isActive: true,
  },
];

// Challenge user statuses (for current user)
export const mockUserChallengeStatuses: UserChallengeStatus[] = [
  {
    id: 'status-1',
    userId: 'user-1',
    challengeId: 'challenge-1',
    status: 'not_started',
    attempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'status-2',
    userId: 'user-1',
    challengeId: 'challenge-2',
    status: 'in_progress',
    startedAt: new Date(),
    attempts: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'status-3',
    userId: 'user-1',
    challengeId: 'challenge-3',
    status: 'completed',
    startedAt: new Date('2024-11-01'),
    completedAt: new Date('2024-11-01'),
    attempts: 1,
    bestSubmissionId: 'submission-1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];